### ISSUE TITLE
cuQuantum appliance. Error detecting nvida GPU

### ISSUE THREAD

**Issue by LB-Navarro** [NVIDIA/cuQuantum#169]
Hi all,
Im trying to run the cuquantum appliance container (cuquantum-appliance:24.03-x86_64) on a virtual machine
kernel: 4.18.0-305.25.1.el8_4.x86_64
OS: Red Hat Enterprise Linux 8.10 (Ootpa)
podman: podman version 4.9.4-rhel

the virtual host machine nvidia-smi command would look like:
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.05    Driver Version: 525.85.05    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GRID A100D-8C       On   | 00000000:00:06.0 Off |                    0 |
| N/A   N/A    P0    N/A /  N/A |      0MiB /  8192MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```
Some hints that something does not run properly:
1) The entrypoint.sh prompts that no nvidia devices are detected. This happens because this shell command fail to match any file:
find /dev -name *nvidia* -type f
The same command would fail on the host machine. 
2) The nvidia-smi command would work inside the container but any attempt to run any of the examples would trigger device errors  
```
python simon.py
Secret string = [0 0 1]
CUDA error: operation not supported device_management.h 64
```
Any hints on what's the issue?
Thanks
luis

**Comment by ymagchi** [comment]
Hi @LB-Navarro,

I would like to check your environments:

1. Could you please check if device files exist in container image with the following command?
```find /dev -name "nvidia*" -type c```

2. Do you use CDI for Podman? I think this issue is not specific to cuQuantum Appliance container and some Podman configs need to be revised. (Please refer to https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html#configuring-podman for CDI setups, https://github.com/containers/podman/issues/9926, https://github.com/NVIDIA/nvidia-container-runtime/issues/85 for related issues).

**Comment by LB-Navarro** [comment]
Hi there,
these are the devices exposed in the container:
```
(container) $ find /dev -name "nvidia*" -type c
/dev/nvidia0
/dev/nvidiactl
/dev/nvidia-uvm-tools
/dev/nvidia-uvm
/dev/nvidia-modeset
```
On your second point, yes I think im using CDI for podman. I had followed the instructions given in the nvidia container toolkit (https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/cdi-support.html) and running 
`sudo podman run -it  --security-opt=label=disable --device=nvidia.com/gpu=all ourmirror_repo/cuquantum-appliance:24.03-x86_64`
Some of the links you referred are older version and/or imply running the container in rootless mode. The weird part is that nvidia-smi, that typically is a good proxy to see that things are going well, gives exactly the same output in the host and in the container, yet the cuquantum examples fail to run properly.

let me know if you need some further info.

**Comment by ymagchi** [comment]
Thank you for the information. Could you please try running with `--privilege` option to see if it results from other security restrictions?

**Comment by LB-Navarro** [comment]
Hi,
It actually made visible the nvidia-cap devices:
```
find /dev -name "nvidia*" -type c
/dev/nvidia0
/dev/nvidiactl
/dev/nvidia-uvm-tools
/dev/nvidia-uvm
/dev/nvidia-modeset
/dev/nvidia-caps/nvidia-cap2
/dev/nvidia-caps/nvidia-cap1
```

- still the container is launched with the "no nvidia devices detected"
- still nvidia-smi is identical to the host machine
- still the examples do not run well

**Comment by ymagchi** [comment]
Thank you for checking that.

Could you please check if CDI are properly configured?

- `podman info | grep -i cgroup` shows that cgroup v2 is used.
- `/etc/nvidia-container-runtime/config.toml` file defines `no-cgroups = false`.
- `sudo nvidia-ctk cdi list` show that `nvidia.com/gpu=all` has been recognized.
- `echo $NVIDIA_DRIVER_CAPABILITIES` inside the image shows `compute,utility`.

If the followings show expected outputs, could you please share the error log by enabling `debug = ...` lines in the `config.toml` file?

**Comment by LB-Navarro** [comment]
I think you've found the root of the problem. Indeed the linux system was using cgroup v1. After switching it to v2 and setting no-cgroups=false, there are some changes. The python examples do not show anymore the previous error. I verified that your point 3 and 4 are also positive. There are a couple of things remaining:
1) The entrypoint script keeps on assessing that there is no gpu functionality
2) the qiskit_ghz.py example does not work

```
$python qiskit_ghz.py 
Traceback (most recent call last):
  File "/home/cuquantum/examples/qiskit_ghz.py", line 42, in <module>
    run(args.nbits, args.precision, not args.disable_cusvaer)
  File "/home/cuquantum/examples/qiskit_ghz.py", line 27, in run
    result = job.result()
  File "/opt/conda/envs/cuquantum-24.03/lib/python3.10/site-packages/qiskit_aer/jobs/utils.py", line 42, in _wrapper
    return func(self, *args, **kwargs)
  File "/opt/conda/envs/cuquantum-24.03/lib/python3.10/site-packages/qiskit_aer/jobs/aerjob.py", line 114, in result
    return self._future.result(timeout=timeout)
  File "/opt/conda/envs/cuquantum-24.03/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/opt/conda/envs/cuquantum-24.03/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/opt/conda/envs/cuquantum-24.03/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/conda/envs/cuquantum-24.03/lib/python3.10/site-packages/qiskit_aer/backends/aerbackend.py", line 414, in _execute_qobj_job
    output = self._cusvaer_execute_qobj(qobj)
  File "/opt/conda/envs/cuquantum-24.03/lib/python3.10/site-packages/qiskit_aer/backends/aer_simulator.py", line 1123, in _cusvaer_execute_qobj
    cusvaer_output = cusvaer_sim._run(qobj, cusvaer_options._fields)
  File "/opt/conda/envs/cuquantum-24.03/lib/python3.10/site-packages/cusvaer/backends/statevector_simulator.py", line 474, in _run
    result = self._run_job(job_id, qobj)
  File "/opt/conda/envs/cuquantum-24.03/lib/python3.10/site-packages/cusvaer/backends/statevector_simulator.py", line 502, in _run_job
    result_list.append(self.run_experiment(experiment))
  File "/opt/conda/envs/cuquantum-24.03/lib/python3.10/site-packages/cusvaer/backends/statevector_simulator.py", line 646, in run_experiment
    cusvsim.apply_queued_gates()
  File "cusvaer/backends/cusvaerext.pyx", line 209, in cusvaer.backends.cusvaerext.CusvSimulator.apply_queued_gates
cusvaer.backends.ubackendext.RuntimeError: cudaErrorNotSupported
```
I assume they signal something is still not quite right. BTW i setup the debug fuctionality but no log has been created so far.

**Comment by ymagchi** [comment]
Thank you for your update.

1.) For the entry point script, I think your output is expected and it needs revisions on our side. We'll work on the fix in a future release.

2.) Regarding the remaining failure, if only `qiskit_ghz.py` has failed, I guess it comes from its memory allocations.

Could you please check if unified memory has been enabled in your environment?  Unified memory may be required for some CUDA memory allocation APIs (e.g., `cudaMallocManaged`, `cudaMallocAsync`), depending on the targeting environment.

Our sample program `deviceQuery` can provide detailed output for the current GPU: [Samples/1_Utilities/deviceQuery/deviceQuery.cpp](https://github.com/NVIDIA/cuda-samples/blob/master/Samples/1_Utilities/deviceQuery/deviceQuery.cpp).
Also, it would be possible to write some code to call `cudaDeviceGetAttribute` as well:
```
int unifiedMemorySupported = 0;
cudaDeviceGetAttribute(&unifiedMemorySupported, cudaDevAttrManagedMemory, 0);
if (unifiedMemorySupported) {
    printf("Unified Memory is supported on this device.\n");
} else {
    printf("Unified Memory is NOT supported on this device.\n");
}
```
For your reference, the docs to enable unified memory on vGPU can be found in the following section:
https://docs.nvidia.com/vgpu/13.0/grid-vgpu-user-guide/index.html#enabling-unified-memory-vgpu

**Comment by LB-Navarro** [comment]
Thanks so much for all this quick feedback. I really appreciate it.
Yes, indeed unified memory is not enabled. I can try to enable it at a later stage but I observed another problem that seems more pressing. 

the issue is that when two containers are launched simultaneously on the host machine, all aparently works but performance drops dramatically (like x100 slower, in fact I thought at the begining the program was frozen). Notice that this has nothing to do with sharing the resource, one of them could be completely inactive and the result is the same. Whatever changes, becomes permanent, meaning returning to a single container does not recover performance. I must reboot the system.
* is that an expected behaviour or it is more of a missconfiguration?

**Comment by ymagchi** [comment]
I think it is expected to see performance drop when multiple container images are launched on the same GPU, as the CUDA contexts could be frequently switched during the computations and resources such as CUDA cores, memory bandwidth, cache could be shared. Once all the computations are done, it would be good to verify that all the CPU/GPU resources are released via `nvidia-smi` and `free`/`vmstat`.

**Comment by LB-Navarro** [comment]
I know how context switching can ruin performance but in this case one of the containers is completely idle, with no GPU usage and the "change" become irreversible, the container/s never show normal performance again, requiring a system reboot. All resources seem to be released properly. 

I'll try to increase the resources of the VM and run a newer kernel but if you could confirm on your end that 2 containers in podman can coexist without performance abnormalities that would help. Get back to you
Thanks
